name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn:
        - "18.3"
        - "19.3"
        - "20.3"
        - "21.3"
        - "22.3"
        - "23.3"
        - "24.0"
        os:
        - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp_vsn}}
        rebar3-version: 3.16.1
    - name: Compile source code
      run: make all
    - name: Run the tests
      run: make tests
